# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.TextField(max_length=100)),
                ('album', models.TextField(max_length=100)),
                ('artista', models.TextField(max_length=100)),
                ('ano', models.DateField(max_length=100)),
                ('valor', models.TextField(max_length=100)),
                ('tipo_articulo', models.IntegerField(choices=[(1, b'Cassete'), (2, b'LP'), (3, b'CD'), (4, b'DVD'), (5, b'VHS')])),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('ped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('num_tel', models.TextField(max_length=12)),
                ('identificacion', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('perfil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='musicshop.Perfil')),
                ('direccion', models.TextField(max_length=200)),
            ],
            bases=('musicshop.perfil',),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('perfil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='musicshop.Perfil')),
                ('codigo', models.TextField(max_length=12)),
            ],
            bases=('musicshop.perfil',),
        ),
        migrations.AddField(
            model_name='pedido',
            name='clt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vnd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.Vendedor'),
        ),
    ]
