# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField()),
                ('art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.Articulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped',
        ),
        migrations.AddField(
            model_name='detalle_p',
            name='r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.Pedido'),
        ),
    ]
