# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0002_auto_20180608_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='odetailt',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicshop.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Seller', 'Vendedor'), ('Client', 'Cliente')], default='Client', max_length=10),
        ),
    ]
