# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0002_auto_20180608_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='album',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='artista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='valor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='identificacion',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='num_tel',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='codigo',
            field=models.CharField(max_length=12),
        ),
    ]
