# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0003_auto_20180608_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
